/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imc;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL-PC
 */
public class FrmImc extends javax.swing.JFrame {

    Imc imc;
    double peso, altura;

    /**
     * Creates new form FrmImc
     */
    public FrmImc() {
        initComponents();
        txtPeso.setText("");
        txtEstatura.setText(""); // en metros
        lblImc.setText("");
        lblEstado.setText("");

        imc = new Imc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEstatura = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblImc = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        lblEstado1 = new javax.swing.JLabel();
        lblImc1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 420));
        setSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("ESTATURA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setText("PESO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, -1, -1));
        getContentPane().add(txtEstatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 110, -1));
        getContentPane().add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 110, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        lblEstado.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblEstado.setText("ESTADO ");
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        lblImc.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblImc.setText("IMC  ");
        getContentPane().add(lblImc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        lblEstado1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblEstado1.setText("Estado : ");
        getContentPane().add(lblEstado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        lblImc1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblImc1.setText("IMC  :");
        getContentPane().add(lblImc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        capDatos();
        double auxImc = imc.calcIMC(peso, altura);
        lblImc.setText(Double.toString(imc.calcIMC(peso, altura)));

        //  if(Math.s) 
        if (auxImc < 18.5) {
            lblEstado.setText("DESNUTRICION");
        } else if (auxImc > 18.5 && auxImc < 25) {
            lblEstado.setText("BAJO DE PESO");
        } else if (auxImc >= 25 && auxImc < 27) {
            lblEstado.setText("NORMOPESO");
        } else if (auxImc >= 27 && auxImc < 30) {
            lblEstado.setText("SOBREPESPO GRADO 1");
        } else if (auxImc >= 30 && auxImc < 35) {
            lblEstado.setText("OBESIDA TIPO 1");
        } else if (auxImc >= 35 && auxImc < 40) {
            lblEstado.setText("OBESIDA TIPO 2");
        } else if (auxImc >= 40 && auxImc < 50) {
            lblEstado.setText("OBESIDA TIPO 3");
        } else if (auxImc > 50) {
            lblEstado.setText("OBESIDA TIPo 4");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    public void capDatos() {
        try {
            peso = Double.parseDouble(txtPeso.getText());
            altura = Double.parseDouble(txtEstatura.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "DATOS INVALIDOS");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmImc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmImc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmImc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmImc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmImc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstado1;
    private javax.swing.JLabel lblImc;
    private javax.swing.JLabel lblImc1;
    private javax.swing.JTextField txtEstatura;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
